[package]
name = "hoshiyomi"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web 框架与异步运行时
axum = "0.8"
tokio = { version = "1", features = ["full"] }

sqlx = { version = "0.9", features = [ "runtime-tokio", "tls-rustls-ring-webpki", "mysql", "chrono" ] }
# 序列化
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
# 环境变量加载
dotenvy = "0.15"

# 日志与跟踪 (推荐)
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
