/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * hoshiyomi API - version 0.1.0
 *
 * hoshiyomi 后端 REST API
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'auth.Auth__jwtEcho': ['GET', '/api/v1/auth/jwt/echo'],
  'auth.Auth__jwtLogin': ['POST', '/api/v1/auth/jwt/login'],
  'auth.Auth__jwtLogout': ['POST', '/api/v1/auth/jwt/logout'],
  'auth.Auth__jwtMe': ['GET', '/api/v1/auth/jwt/me'],
  'auth.Auth__jwtRefresh': ['POST', '/api/v1/auth/jwt/refresh'],
  'auth.Auth__login': ['POST', '/api/v1/auth/login'],
  'auth.Auth__logout': ['POST', '/api/v1/auth/logout'],
  'auth.Auth__me': ['GET', '/api/v1/auth/me'],
  'auth.Auth__register': ['POST', '/api/v1/auth/register'],
  'health.Health__check': ['GET', '/api/v1/health'],
  'user.User__list': ['GET', '/api/v1/users'],
  'user.User__create': ['POST', '/api/v1/users'],
  'user.User__get': ['GET', '/api/v1/users/{id}'],
  'user.User__delete': ['DELETE', '/api/v1/users/{id}'],
  'user.User__changePassword': ['PUT', '/api/v1/users/{id}/password'],
  'user.User__updateUsername': ['PUT', '/api/v1/users/{id}/username']
};
