/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum - version 0.2.0
 *
 * Utoipa&#x27;s axum bindings for seamless integration for the two
 *
 * OpenAPI version: 3.1.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface LoginReq {
  password: string;
  username: string;
}
export interface RefreshReq {
  refresh_token: string;
}
export interface RegisterReq {
  email: string;
  password: string;
  username: string;
}
export interface ApiResponse_JwtEchoResp {
  code: number;
  data?: {
    user_id: number;
    username: string;
  };
  errors?: object;
  message: string;
}
export interface ApiResponse_MessageResp {
  code: number;
  data?: {
    message: string;
  };
  errors?: object;
  message: string;
}
export type Perm =
  '*' | 'user:read' | 'user:write' | 'user:delete' | 'user:*' | 'role:read' | 'role:write' | 'role:delete' | 'role:*';
export interface UserResp {
  created_at: string;
  email: string;
  id: number;
  updated_at: string;
  username: string;
}
export interface ApiResponse_AuthStateResp {
  code: number;
  data?: {
    permissions: Perm[];
    user: UserResp;
  };
  errors?: object;
  message: string;
}
export interface ApiResponse_String {
  code: number;
  data?: string;
  errors?: object;
  message: string;
}
export interface ApiResponse_UserResp {
  code: number;
  data?: {
    created_at: string;
    email: string;
    id: number;
    updated_at: string;
    username: string;
  };
  errors?: object;
  message: string;
}
export interface ChangePasswordReq {
  new_password: string;
  old_password: string;
}
export interface UpdateUsernameReq {
  username: string;
}
export interface AuthStateResp {
  permissions: Perm[];
  user: UserResp;
}
export interface ApiResponse_LoginResp {
  code: number;
  data?: {
    access_token: string;
    refresh_token: string;
    state: AuthStateResp;
  };
  errors?: object;
  message: string;
}
export interface ApiResponse_RefreshResp {
  code: number;
  data?: {
    access_token: string;
    refresh_token: string;
  };
  errors?: object;
  message: string;
}
export interface ApiResponse_PageData_UserResp {
  code: number;
  /**
   * 分页数据载荷
   */
  data?: {
    items: Array<{
      created_at: string;
      email: string;
      id: number;
      updated_at: string;
      username: string;
    }>;
    page: number;
    per_page: number;
    total: number;
  };
  errors?: object;
  message: string;
}
declare global {
  interface Apis {
    auth: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/auth/jwt/echo
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     user_id: number
       *     username: string
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      Auth__jwtEcho<Config extends Alova2MethodConfig<ApiResponse_JwtEchoResp>>(
        config?: Config
      ): Alova2Method<ApiResponse_JwtEchoResp, 'auth.Auth__jwtEcho', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/auth/jwt/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   password: string
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     access_token: string
       *     refresh_token: string
       *     state: {
       *       // [items] start
       *       // 权限点:serde 与 strum 序列化码必须一致(见 tests::test_permissions_consistency)
       *       // [items] end
       *       permissions: (
       *         | '*'
       *         | 'user:read'
       *         | 'user:write'
       *         | 'user:delete'
       *         | 'user:*'
       *         | 'role:read'
       *         | 'role:write'
       *         | 'role:delete'
       *         | 'role:*'
       *       )[]
       *       user: {
       *         created_at: string
       *         email: string
       *         id: number
       *         updated_at: string
       *         username: string
       *       }
       *     }
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      Auth__jwtLogin<
        Config extends Alova2MethodConfig<ApiResponse_LoginResp> & {
          data: LoginReq;
        }
      >(
        config: Config
      ): Alova2Method<ApiResponse_LoginResp, 'auth.Auth__jwtLogin', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/auth/jwt/logout
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     message: string
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      Auth__jwtLogout<Config extends Alova2MethodConfig<ApiResponse_MessageResp>>(
        config?: Config
      ): Alova2Method<ApiResponse_MessageResp, 'auth.Auth__jwtLogout', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/auth/jwt/me
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     // [items] start
       *     // 权限点:serde 与 strum 序列化码必须一致(见 tests::test_permissions_consistency)
       *     // [items] end
       *     permissions: (
       *       | '*'
       *       | 'user:read'
       *       | 'user:write'
       *       | 'user:delete'
       *       | 'user:*'
       *       | 'role:read'
       *       | 'role:write'
       *       | 'role:delete'
       *       | 'role:*'
       *     )[]
       *     user: {
       *       created_at: string
       *       email: string
       *       id: number
       *       updated_at: string
       *       username: string
       *     }
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      Auth__jwtMe<Config extends Alova2MethodConfig<ApiResponse_AuthStateResp>>(
        config?: Config
      ): Alova2Method<ApiResponse_AuthStateResp, 'auth.Auth__jwtMe', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/auth/jwt/refresh
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   refresh_token: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     access_token: string
       *     refresh_token: string
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      Auth__jwtRefresh<
        Config extends Alova2MethodConfig<ApiResponse_RefreshResp> & {
          data: RefreshReq;
        }
      >(
        config: Config
      ): Alova2Method<ApiResponse_RefreshResp, 'auth.Auth__jwtRefresh', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/auth/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   password: string
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     // [items] start
       *     // 权限点:serde 与 strum 序列化码必须一致(见 tests::test_permissions_consistency)
       *     // [items] end
       *     permissions: (
       *       | '*'
       *       | 'user:read'
       *       | 'user:write'
       *       | 'user:delete'
       *       | 'user:*'
       *       | 'role:read'
       *       | 'role:write'
       *       | 'role:delete'
       *       | 'role:*'
       *     )[]
       *     user: {
       *       created_at: string
       *       email: string
       *       id: number
       *       updated_at: string
       *       username: string
       *     }
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      Auth__login<
        Config extends Alova2MethodConfig<ApiResponse_AuthStateResp> & {
          data: LoginReq;
        }
      >(
        config: Config
      ): Alova2Method<ApiResponse_AuthStateResp, 'auth.Auth__login', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/auth/logout
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     message: string
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      Auth__logout<Config extends Alova2MethodConfig<ApiResponse_MessageResp>>(
        config?: Config
      ): Alova2Method<ApiResponse_MessageResp, 'auth.Auth__logout', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/auth/me
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     // [items] start
       *     // 权限点:serde 与 strum 序列化码必须一致(见 tests::test_permissions_consistency)
       *     // [items] end
       *     permissions: (
       *       | '*'
       *       | 'user:read'
       *       | 'user:write'
       *       | 'user:delete'
       *       | 'user:*'
       *       | 'role:read'
       *       | 'role:write'
       *       | 'role:delete'
       *       | 'role:*'
       *     )[]
       *     user: {
       *       created_at: string
       *       email: string
       *       id: number
       *       updated_at: string
       *       username: string
       *     }
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      Auth__me<Config extends Alova2MethodConfig<ApiResponse_AuthStateResp>>(
        config?: Config
      ): Alova2Method<ApiResponse_AuthStateResp, 'auth.Auth__me', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/auth/register
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   email: string
       *   password: string
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     created_at: string
       *     email: string
       *     id: number
       *     updated_at: string
       *     username: string
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      Auth__register<
        Config extends Alova2MethodConfig<ApiResponse_UserResp> & {
          data: RegisterReq;
        }
      >(
        config: Config
      ): Alova2Method<ApiResponse_UserResp, 'auth.Auth__register', Config>;
    };
    health: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/health
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: string
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      Health__check<Config extends Alova2MethodConfig<ApiResponse_String>>(
        config?: Config
      ): Alova2Method<ApiResponse_String, 'health.Health__check', Config>;
    };
    user: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/users
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 页码,从 1 开始
       *   page?: number
       *   // 每页条数,1-100
       *   per_page?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   // 分页数据载荷
       *   data?: {
       *     // [items] start
       *     // [items] end
       *     items: Array<{
       *       created_at: string
       *       email: string
       *       id: number
       *       updated_at: string
       *       username: string
       *     }>
       *     page: number
       *     per_page: number
       *     total: number
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      User__list<
        Config extends Alova2MethodConfig<ApiResponse_PageData_UserResp> & {
          params: {
            /**
             * 页码,从 1 开始
             */
            page?: number;
            /**
             * 每页条数,1-100
             */
            per_page?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResponse_PageData_UserResp, 'user.User__list', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/v1/users
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     created_at: string
       *     email: string
       *     id: number
       *     updated_at: string
       *     username: string
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      User__create<Config extends Alova2MethodConfig<ApiResponse_UserResp>>(
        config?: Config
      ): Alova2Method<ApiResponse_UserResp, 'user.User__create', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/v1/users/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 用户 ID
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     created_at: string
       *     email: string
       *     id: number
       *     updated_at: string
       *     username: string
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      User__get<
        Config extends Alova2MethodConfig<ApiResponse_UserResp> & {
          pathParams: {
            /**
             * 用户 ID
             */
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResponse_UserResp, 'user.User__get', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/v1/users/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 用户 ID
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     message: string
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      User__delete<
        Config extends Alova2MethodConfig<ApiResponse_MessageResp> & {
          pathParams: {
            /**
             * 用户 ID
             */
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ApiResponse_MessageResp, 'user.User__delete', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/v1/users/{id}/password
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 用户 ID
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   new_password: string
       *   old_password: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     message: string
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      User__changePassword<
        Config extends Alova2MethodConfig<ApiResponse_MessageResp> & {
          pathParams: {
            /**
             * 用户 ID
             */
            id: number;
          };
          data: ChangePasswordReq;
        }
      >(
        config: Config
      ): Alova2Method<ApiResponse_MessageResp, 'user.User__changePassword', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/v1/users/{id}/username
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 用户 ID
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   data?: {
       *     created_at: string
       *     email: string
       *     id: number
       *     updated_at: string
       *     username: string
       *   }
       *   errors?: object
       *   message: string
       * }
       * ```
       */
      User__updateUsername<
        Config extends Alova2MethodConfig<ApiResponse_UserResp> & {
          pathParams: {
            /**
             * 用户 ID
             */
            id: number;
          };
          data: UpdateUsernameReq;
        }
      >(
        config: Config
      ): Alova2Method<ApiResponse_UserResp, 'user.User__updateUsername', Config>;
    };
  }

  var Apis: Apis;
}
