CREATE TABLE users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP())
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
