/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
  }
}
